### ISSUE TITLE
License must be included with my buttonapi.

### ISSUE THREAD

**Issue by MistressPlague** [LargestBoi/A.R.E.S#14]
Otherwise I will need to do a takedown request.

Follow the licensing.

**Comment by WOLFIE-OG** [comment]
> Otherwise I will need to do a takedown request.
> 
> Follow the licensing.

Shuuush plague you smell

**Comment by LargestBoi** [comment]
Please take a look at our current V10 code, we have dropped your API as a dependency and have instead moved to ReMod.Core

**Comment by LargestBoi** [comment]
This is further proven by our current version of the ARES Logger right here:
https://github.com/LargestBoi/A.R.E.S/blob/main/A.R.E.S%20Logger/AvatarLogger.cs

Here are the specific code implementations within the file:
https://i.imgur.com/Y7B7yQi.png
https://i.imgur.com/wFS6XEi.png

There isn't even a mention of the ButtonAPI itself anymore ;-;
https://i.imgur.com/r7DrKh2.png

**Comment by cznm** [comment]
femboy cope

**Comment by MistressPlague** [comment]
Aight bet, dmca finna be funny as you fail to notice you have included my work in this repo. Look again.

**Comment by LargestBoi** [comment]
Did I leave the DLL somewhere by mistake?

**Comment by MistressPlague** [comment]
You have.

**Comment by LargestBoi** [comment]
Could you be so kind as to link the file?, We don't use the DLL anymore it is just taking up space on the repo without being used anywhere

**Comment by LargestBoi** [comment]
Ah NVM found it, it was in our DLLs folder since it used to be a requirement yet wasn't deleted yet, when I am at a PC I'll make a lush removing the DLL.

**Comment by MistressPlague** [comment]
Provided it is done before github looks at the dmca, you will be fine. 

I'm happy for use of my api, just not when the license is not followed.
Of which my api now has a auto updater and all.

**Comment by LargestBoi** [comment]
Yeah we have completely dropped the usage of the API and moved to ReMod.Core the left over DLL is simply a relic that was mistakenly not removed👌

**Comment by MistressPlague** [comment]
All good, I contacted GitHub to cancel the DMCA, but on the chance they don't listen, just be sure it is removed soon.

You should be able to remove it on mobile.

**Comment by MistressPlague** [comment]
Just take this to learn; be very careful when using libraries to follow licenses. I would check if ReMod.Core has one that may need included too.

**Comment by LargestBoi** [comment]
No troubles, I'll be at my PC shortly

**Comment by WOLFIE-OG** [comment]
> Just take this to learn; be very careful when using libraries to follow licenses. I would check if ReMod.Core has one that may need included too.
  

![image](https://user-images.githubusercontent.com/35380754/147410209-5157743e-a085-49c3-bc41-e8075d3f23b7.jpeg)

**Comment by MistressPlague** [comment]
You also might want to state in the readme which libraries you are using, and to link their orig repo's, along with linking your license file for such. Makes it much more clear when they view your repo.

**Comment by MistressPlague** [comment]
> 

My god it is obvious you don't understand GitHub licensing and how serious it can get xD
Licenses for libraries or software is a pretty important topic. I'm not even the first to open a issue regarding this.

**Comment by LargestBoi** [comment]
Yeah I belive I placed most of the important ones there already 👌

**Comment by LargestBoi** [comment]
> > 
> Licenses for libraries or software is a pretty important topic. I'm not even the first to open a issue regarding this.


Yeah U right, just easy to mistake is all👌

**Comment by MistressPlague** [comment]
You're pretty chill, though.

**Comment by LargestBoi** [comment]
At the end of the day it's just an honest mistake, nothing to create hate over, this stuff is is best resolved quickly and formally👌

**Comment by MistressPlague** [comment]
Exactly.

**Comment by WOLFIE-OG** [comment]
> > Reply To Wolfie:
> 
> My god it is obvious you don't understand GitHub licensing and how serious it can get xD
> 
> Licenses for libraries or software is a pretty important topic. I'm not even the first to open a issue regarding this.

It's obvious you can't tell if some one is shitposting

**Comment by LargestBoi** [comment]
Imma lock the issue to prevent any possible further shitposting🤣
