### ISSUE TITLE
Auto-Updater Plugin Possible Mem-Leak

### ISSUE THREAD

**Issue by MistressPlague** [LargestBoi/A.R.E.S#15]
In the plugin, DownloadMod uses a delegate expression (aka lambda) to a new webclient. This client is never disposed and a new one is made each call.

I recommend changing to using a "using" scope, so it is auto-disposed after use. Note this would need a method body.

**Comment by LargestBoi** [comment]
I have contacted you/friended you via discord just to make communication easier, I'll look into the issue later on and try patch it out. Thank you for pointing it out tho, our mod also keeps the plugin up to date, does the download plugin function also have this possible memory leak issue?

**Comment by MistressPlague** [comment]
Likely, when a lambda is made, it is effectively like a code block, in turn what it leads to is repeated. Thus in the case i mentioned which i noticed, new WebClient() repeats, and there's no disposal of said made client.

We'll chat on discord.
